# Site Info
title: goodbaam's blog
tagline: 'for data'
description: 'blog for data'
url: http://goodbaam.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: GoodBaam
  description: <strong>굿 밤</strong> 잠은 자가면서 하자!
  #gravatar: <hide>
  contact:
    #linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/goodbaam
    #facebook:  https://www.facebook.com/gichanglee.84
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:gichang_lee@korea.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://goodbaam.github.io/public/img/picture.JPG
  caption: 없음

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'goodbaam-github-io' # leave blank if you don't want disqus

